# Generated by Django 5.1 on 2024-09-12 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام دسته بندی ')),
                ('image', models.ImageField(blank=True, default='media/imgae/default.png', null=True, upload_to='image/', verbose_name='عکس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='نام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('price', models.BigIntegerField(default=0, verbose_name='قیمت')),
                ('pr_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ تولید')),
                ('exp_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انقضا')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='برند')),
                ('image', models.ImageField(blank=True, default='media/image/default.png', null=True, upload_to='image/', verbose_name='عکس')),
                ('purchase_count', models.PositiveIntegerField(default=0, verbose_name='تعداد خرید')),
                ('status', models.CharField(choices=[('in_stock', 'موجود'), ('out_of_stock', 'ناموجود'), ('coming_soon', 'به زودی')], default='in_stock', max_length=20, verbose_name='وضعیت')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='بدون نظر', verbose_name='نظر')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='product.productinfo', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productinfo')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
